- name: Deploy Dockerized Flask App
  hosts: web
  become: yes
  vars:
    service_name: service1  # default value, can be overridden
    docker_image: doronsun/myflaskapp-service1:latest  # default value, can be overridden
    container_port: 5000  # default value, can be overridden

  tasks:
    - name: Stop and remove old containers using the same port
      shell: |
        docker ps -q --filter "publish={{ container_port }}" | xargs -r docker rm -f
        docker rm -f {{ service_name }} || true

    - name: Pull latest Docker image
      shell: docker pull {{ docker_image }}

    - name: Run new container
      shell: >
        docker run -d 
        --name {{ service_name }} 
        -p {{ container_port }}:{{ container_port }} 
        {{ docker_image }}


