- name: Deploy Dockerized Flask App
  hosts: web
  become: yes
  tasks:
    - name: Remove existing container (if any)
      shell: docker rm -f flask-app || true

    - name: Pull latest Docker image
      shell: docker pull doronsun/myflaskapp:latest

    - name: Run new container
      shell: docker run -d --name flask-app -p 5000:5000 doronsun/myflaskapp:latest


